import sys
sys.path.append("System")
sys.path.append("Library")
sys.path.append("Devices")
sys.path.append("Devices/GPS")
sys.path.append("Devices/GSM")
sys.path.append("Devices/Modem")
sys.path.append("Devices/NetworkPerformance")
sys.path.append("Devices/Switch")
sys.path.append("Devices/VSAT")
sys.path.append("Devices/FBB")
sys.path.append("Devices/IOP")
sys.path.append("Devices/SNMP")
sys.path.append("Devices/PowerSwitch")
sys.path.append("Devices/PLC")
sys.path.append("Devices/BWTS")
sys.path.append("Devices/Mediator")
sys.path.append("Devices/NMEA")
sys.path.append("Devices/VDR")
sys.path.append("Devices/Router")
sys.path.append("Devices/SATC")
sys.path.append("Devices/VHF")
sys.path.append("Devices/AlarmPanel")

